spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab14_part2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  ai:
    openai:
      api-key: {OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o


  logging:
  level:
    org:
      springframework: INFO








